openapi: 3.0.3
info:
  title: Swiss Stage Web - 認証API
  description: Google OAuth2ログイン認証のREST APIエンドポイント定義
  version: 1.0.0
  contact:
    name: Swiss Stage Web Team

servers:
  - url: http://localhost:8080/api
    description: ローカル開発環境
  - url: https://your-domain.com/api
    description: 本番環境

tags:
  - name: Authentication
    description: 認証関連エンドポイント

paths:
  /auth/google:
    get:
      summary: Google OAuth2認証開始
      description: Google OAuth2認証フローを開始し、Googleの同意画面にリダイレクトします
      operationId: initiateGoogleLogin
      tags:
        - Authentication
      responses:
        '302':
          description: Googleの認証画面にリダイレクト
          headers:
            Location:
              description: Googleの認証URL
              schema:
                type: string
                example: https://accounts.google.com/o/oauth2/v2/auth?client_id=...
        '500':
          description: サーバーエラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /auth/google/callback:
    get:
      summary: Google OAuth2コールバック
      description: Google OAuth2認証後のコールバックエンドポイント。JWTトークンを生成し、HTTP-only Cookieに保存してフロントエンドにリダイレクトします
      operationId: handleGoogleCallback
      tags:
        - Authentication
      parameters:
        - name: code
          in: query
          description: Googleから返される認証コード
          required: true
          schema:
            type: string
        - name: state
          in: query
          description: CSRF保護用のstateパラメータ
          required: true
          schema:
            type: string
      responses:
        '302':
          description: ダッシュボードにリダイレクト
          headers:
            Location:
              description: フロントエンドのダッシュボードURL
              schema:
                type: string
                example: http://localhost:3000/dashboard
            Set-Cookie:
              description: JWT_TOKEN (HTTP-only, Secure, SameSite=Strict, 24時間有効)
              schema:
                type: string
                example: JWT_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...; HttpOnly; Secure; SameSite=Strict; Max-Age=86400; Path=/
        '400':
          description: 不正なリクエスト（codeまたはstateが無効）
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: 認証失敗
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: サーバーエラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /auth/me:
    get:
      summary: 現在のユーザー情報取得
      description: JWTトークンから現在ログイン中のユーザー情報を取得します
      operationId: getCurrentUser
      tags:
        - Authentication
      security:
        - CookieAuth: []
      responses:
        '200':
          description: ユーザー情報取得成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '401':
          description: 未認証（JWTトークンが無効または期限切れ）
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /auth/logout:
    post:
      summary: ログアウト
      description: JWTトークンを無効化し、HTTP-only Cookieを削除します
      operationId: logout
      tags:
        - Authentication
      security:
        - CookieAuth: []
      responses:
        '200':
          description: ログアウト成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: ログアウトしました
          headers:
            Set-Cookie:
              description: JWT_TOKENを削除するCookie
              schema:
                type: string
                example: JWT_TOKEN=; HttpOnly; Secure; SameSite=Strict; Max-Age=0; Path=/
        '401':
          description: 未認証
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    CookieAuth:
      type: apiKey
      in: cookie
      name: JWT_TOKEN
      description: HTTP-only Cookieに保存されたJWTトークン

  schemas:
    UserResponse:
      type: object
      description: ユーザー情報レスポンス（個人情報はマスキング済み）
      required:
        - userId
        - displayName
        - createdAt
        - lastLoginAt
      properties:
        userId:
          type: string
          format: uuid
          description: ユーザーの一意識別子
          example: 550e8400-e29b-41d4-a716-446655440000
        displayName:
          type: string
          description: Googleアカウントの表示名
          minLength: 1
          maxLength: 100
          example: 山田太郎
        createdAt:
          type: string
          format: date-time
          description: アカウント作成日時（ISO 8601形式）
          example: 2025-12-31T00:00:00Z
        lastLoginAt:
          type: string
          format: date-time
          description: 最終ログイン日時（ISO 8601形式）
          example: 2025-12-31T12:30:00Z
      example:
        userId: 550e8400-e29b-41d4-a716-446655440000
        displayName: 山田太郎
        createdAt: 2025-12-31T00:00:00Z
        lastLoginAt: 2025-12-31T12:30:00Z

    ErrorResponse:
      type: object
      description: エラーレスポンス
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: エラーコード
          example: AUTHENTICATION_FAILED
        message:
          type: string
          description: ユーザーフレンドリーなエラーメッセージ（日本語）
          example: 認証に失敗しました。再度お試しください
        details:
          type: string
          description: 詳細なエラー情報（開発環境のみ表示）
          example: Invalid OAuth2 code
      example:
        error: AUTHENTICATION_FAILED
        message: 認証に失敗しました。再度お試しください

  examples:
    AuthenticationFailedError:
      value:
        error: AUTHENTICATION_FAILED
        message: 認証に失敗しました。再度お試しください

    UnauthorizedError:
      value:
        error: UNAUTHORIZED
        message: ログインが必要です

    InvalidTokenError:
      value:
        error: INVALID_TOKEN
        message: セッションが無効です。再度ログインしてください
